apiVersion: v1
kind: Service
metadata:
  name: kubeslice-dns
  namespace: kubeslice-system
  labels:
    app: kubeslice-dns
spec:
  type: ClusterIP
  selector:
    app: kubeslice-dns
  ports:
  - port: 53
    protocol: UDP
    name: udp-53
    targetPort: 1053
  - port: 53
    protocol: TCP
    name: tcp-53
    targetPort: 1053
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeslice-dns
  namespace: kubeslice-system
  labels:
    app: kubeslice-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeslice-dns
  template:
    metadata:
      labels:
        app: kubeslice-dns
        avesha.io/pod-type: dns
    spec:
      serviceAccount: kubeslice-dns
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: avesha/node-type
                operator: In
                values:
                - gateway
      terminationGracePeriodSeconds: 30
      dnsPolicy: Default
      imagePullSecrets:
      - name: avesha-nexus
      containers:
      - name: "dns"
        image: "docker.io/aveshasystems/dns:0.0.1"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 1053
          protocol: UDP
          name: udp-53
        - containerPort: 1053
          protocol: TCP
          name: tcp-53
      tolerations:
        - key: "avesha/node-type"
          operator: "Equal"
          value: "gateway"
          effect: "NoSchedule"
        - key: "avesha/node-type"
          operator: "Equal"
          value: "gateway"
          effect: "NoExecute"
