apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeslice-dns
  namespace: kubeslice-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeslice-dns-role
  namespace: kubeslice-system
rules:
- apiGroups:
  - mesh.avesha.io
  resources:
  - serviceexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.avesha.io
  resources:
  - serviceexports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mesh.avesha.io
  resources:
  - serviceimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.avesha.io
  resources:
  - serviceimports/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeslice-dns-rolebinding
  namespace: kubeslice-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeslice-dns-role
subjects:
- kind: ServiceAccount
  name: kubeslice-dns
  namespace: kubeslice-system

