name: build-test-kubeslice-dns
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2
        with:
          tags: kubeslice-dns:latest
          push: false
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2
        with:
          file: test.Dockerfile
          tags: test-image:latest
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: make test
